require("plugins.plugins-setup")
require("core.options")
require("core.keymaps")
--- 插件
require("plugins.lualine")
require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/cmp")
require("plugins/lsp")
require("plugins/comment")
require("plugins/autopairs")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins/fzf")
